### ISSUE TITLE
Integration tests that demonstrate QoS behaviour

### ISSUE THREAD

**Issue by michaelklishin** [clojurewerkz/machine_head#1]
We need to add some integration tests that actually demonstrate how QoS works as opposed to simply specifying a value to various functions but never asserting on QoS-related behaviour.

**Comment by jakubholynet** [comment]
Do you have any idea how to do that? We don't know (or care) what Paho does with the value internally. We should only care that we pass it correctly on to Paho. I.e. we should not test that Paho behaves according to the specified QoS, that is a Paho, not mh test. And writing a test to check that we pass it to it in all relevant methods and do so correctly sounds a little like testing a getter - i.e. little value for, in this case, possibly lot of work. I propose to close this as "won't fix".

**Comment by michaelklishin** [comment]
Tests have multiple purposes. One is making sure that the code works as expected. Another is assumption verification. Another still is examples that can trivially be ported to doc guides.

The goal of this issue is primarily the latter.

**Comment by michaelklishin** [comment]
Actually, I now re-read the description and looks like I was pretty unsure of that myself. Let's close it. If it's an actual behaviour worth testing in our suite, it will resurface eventually.
