### ISSUE TITLE
core.async?

### ISSUE THREAD

**Issue by kenrestivo** [clojurewerkz/machine_head#19]
I have been starting to use machine-head in a project, and I find myself craving a core.async-based API, more along the lines of https://github.com/bguthrie/async-sockets

Would you want something like that included in machine-head? Or would it complect it unnecessarily?

No big deal if not, I'll probably either write my own library that either depends on machine-head or forks it.

**Comment by michaelklishin** [comment]
You can always develop your own library that bridges `core.async` and Machine Head/Langohr/etc. I have absolutely 0 interest in adding a `core.async` dependency to any ClojureWerkz projects: there is no justification for that.
