### ISSUE TITLE
Release 1.0.0

### ISSUE THREAD

**Issue by jakubholynet** [clojurewerkz/machine_head#26]
I see that machine head has been in "beta" for quite a while. Given that and the low number of issues here, it is perhaps ready to release 1.0.0? If not - what is missing / needed?

Thanks!

**Comment by michaelklishin** [comment]
Issues such as #13, outstanding PRs, documentation guides review.

**Comment by jakubholynet** [comment]
I see there is a single issue+PR plus one testing task. Both have been inactive for almost three years. So perhaps they are not so important after all?

Could you be more specific about "documentation guides review"? Is that something I could help with?

**Comment by michaelklishin** [comment]
We need to fix all outstanding issues and go through the docs, updating them as needed. We also need to make sure that there are no glaring holes around key features. The docs haven't had a review in at least a couple of years.

**Comment by jakubholynet** [comment]
The last outstanding issue (#13) will hopefully be fixed soon. I can go through the docs and check and update them, though I do not have enough material to add new guides, if you feel that we need some.

> make sure that there are no glaring holes around key features

How should we do that, practically speaking?

**Comment by jakubholynet** [comment]
The docs have been updated (though I see that not published yet). Is there any other obstacle on the way to v. 1.0.0?

**Comment by michaelklishin** [comment]
Not that I'm aware of. Will do a release some time this week. Thank you.

**Comment by jakubholynet** [comment]
@michaelklishin I see the release hasn't happened. Any ETA? Thx!

**Comment by michaelklishin** [comment]
Sorry about that. I should get to it tomorrow.

**Comment by michaelklishin** [comment]
@jakubholynet I haven't forgotten about this :)
