### ISSUE TITLE
How to handle MQTT_KEEP_ALIVE_TIMEOUT disconnect?

### ISSUE THREAD

**Issue by glenthomas** [clojurewerkz/machine_head#36]
For machine_head 1.0.0 with AWS IoT MQTT.
I am using connect options as below:

```
{:on-connect-complete (fn [_ reconnection? server-uri]
  (log/info (if reconnection? "reconnected" "connected") "to" server-uri))
  :on-connection-lost  (fn [reason]
    (log/warn "connection lost:" reason))
  :client-id (str "client-" (str (UUID/randomUUID)))
  :opts  {:socket-factory socket-factory
              :auto-reconnect true
              :clean-session  false}}
```

In the AWS IoT logs I can see this disconnect event logged:

```json
{
    "timestamp": "2022-01-26 14:55:18.467",
    "logLevel": "INFO",
    "traceId": "e9c8a069-700b-1b9b-9288-c15fe84fc522",
    "accountId": "123456789012",
    "status": "Success",
    "eventType": "Disconnect",
    "protocol": "MQTT",
    "clientId": "client-9b3fe2f7-f962-4e03-892c-d6a661d0d3e1",
    "principalId": "9ba1cd8b6a7925833e460593461b7597581ddead9a065abf35346f8e537dffce",
    "sourceIp": "21.356.16.092",
    "sourcePort": 36532,
    "disconnectReason": "MQTT_KEEP_ALIVE_TIMEOUT"
}
```

Even with `auto-reconnect` set to `true` the client did not reconnect and resume processing.

How should I handle this scenario using machine_head?

**Comment by SignSpice** [comment]
@glenthomas Running into the same issue. I'll let you know when I find a solution.

**Comment by michaelklishin** [comment]
Machine Head does not support this option, you are welcome to add it. This is open source software after all.

**Comment by glenthomas** [comment]
> Machine Head does not support this option, you are welcome to add it. This is open source software after all.

Are you saying machine head does not support the `auto-reconnect` option and setting it to true/false has no effect?
I thought that machine head was just a wrapper for the paho client and paho would handle the reconnect option.

**Comment by michaelklishin** [comment]
@glenthomas huh? the title of the issue talks about keepalive timeouts. It's not an option exposed to Clojure. All Paho Java client options you want exposed must be explicitly listed and "propagated", Machine Head does not magically discover them via reflection or something like that.

**Comment by michaelklishin** [comment]
Here are the [exposed options](https://github.com/clojurewerkz/machine_head/blob/master/src/clojure/clojurewerkz/machine_head/client.clj#L21-L48). One of them is a keepalive interval, which IIRC is not the same as a keepalive *timeout*.

Adding support for more options should be trivial. PRs would be appreciated.

**Comment by glenthomas** [comment]
The **automatic reconnect** feature is documented by Paho as

> The ability for the client library to reconnect automatically in the event of a connection failure.

I had expected connection failure to include a connection being closed by the MQTT broker due to keep alive timeout.

**Comment by michaelklishin** [comment]
@glenthomas all this library does is [propagate some options to Paho](https://github.com/clojurewerkz/machine_head/blob/master/src/clojure/clojurewerkz/machine_head/conversion.clj#L25). You are welcome to investigate what's going on using a traffic capture.
I cannot possibly suggest much without any steps to reproduce. Guessing is a really expensive approach to debugging.

**Comment by glenthomas** [comment]
@michaelklishin I simply came here looking for some help as a consumer of this package. I feel like I have caused stress and inconvenience. I will close this issue and be on my way. Sorry to have disturbed you.

**Comment by SignSpice** [comment]
@glenthomas So I have tried a few things to work around this problem, but what finally worked was to make a keep-alive topic and publish every minute. Probably does not even need that frequently.   I am using chime https://github.com/jarohen/chime. Works like a charm. :)
