### ISSUE TITLE
clojuremqtt.info has expired

### ISSUE THREAD

**Issue by Olical** [clojurewerkz/machine_head#37]
I _think_ the domain name has expired, I can't seem to get to the docs website and I think it's trying to show me a namecheap webpage?

Worth moving this to GitHub pages or something and using a GitHub domain to avoid having to worry about it?

**Comment by michaelklishin** [comment]
You can [find the docs here](https://github.com/clojurewerkz/machine_head.docs). Perhaps we should simply move them to this repo, they are bare Markdown files that would be readable right here on GitHub.
